Initial Structure
invopop/gobl.verifactu pull request #1
Opened 2024-11-04 13:42 UTC by apardods

2024-12-16 10:01 UTC, samlown requested changes
In general looking really good! nice one! Ideally we'd have the names of everything in English, but for the time being I'd focussing on ensuring the public **methods** and configuration structures are all in English.

2024-12-16 10:01 UTC, samlown commented on README.md
> +The following extensions must be added to the document:
I'd add here that the GOBL addon will automatically add these extensions.

2024-12-16 10:01 UTC, samlown commented on doc/document.go
> +}
As these names are exposed to external usage, they should be in English, or utilise an external wrapper.

2024-12-16 10:01 UTC, samlown commented on doc/errors.go
> +	ErrInvalid    = newError("invalid")
I'd rename this to `ErrValidation`. Naming gets a bit confusing otherwise (I had this problem in TicketBAI and refactored to `validation`).

2024-12-16 10:01 UTC, samlown commented on doc/fingerprint.go
> +	Huella                 string `json:"huella"`
These for sure should be in English!

2024-12-16 10:01 UTC, samlown commented on doc/doc.go
> +}
This is a bit confusing. Should it not be mixed in with the other errors?

2024-12-16 10:01 UTC, samlown commented on doc/errors.go
> +var ErrorCodes = map[string]string{
Does the remove system not provide these error messages? For sure they should be translated if we're using our own local copies.

2024-12-16 10:01 UTC, samlown commented on doc/fingerprint.go
> +func (d *VeriFactu) generateHashAlta(prev *ChainData) error {
comment and method name miss-match

2024-12-16 10:01 UTC, samlown commented on doc/invoice.go
> +func NewRegistroAlta(inv *bill.Invoice, ts time.Time, r IssuerRole, s *Software) (*RegistroAlta, error) {
English.

2024-12-16 10:01 UTC, samlown commented on internal/gateways/gateways.go
> +		c.client.SetBaseURL(ProductionBaseURL)
I'd raise an error here to indicate that production is not yet supported.

2024-12-16 10:41 UTC, apardods commented
Added all the changes mentioned. Still missing translating all field names but will leave that as is to focus on app

2024-12-19 13:47 UTC, samlown approved these changes

2024-12-19 13:53 UTC, merged